export default [
  { id: 1, type: "dare", content: "Tell a funny joke." },
  { id: 2, type: "dare", content: "Sing your favorite song." },
  { id: 3, type: "dare", content: "Do a dance move." },
  { id: 4, type: "dare", content: "Try a food you've never had before." },
  { id: 5, type: "dare", content: "Take a shot of liquor." },
  { id: 6, type: "dare", content: "Recreate a famous movie scene." },
  { id: 7, type: "dare", content: "Do a handstand or attempt a yoga pose." },
  { id: 8, type: "dare", content: "Learn a few phrases in a foreign language and say them out loud." },
  { id: 9, type: "dare", content: "Give a random compliment to a stranger." },
  { id: 10, type: "dare", content: "Try a challenging physical activity or sport you've never done before." },
  { id: 11, type: "dare", content: "Perform a karaoke song." },
  { id: 12, type: "dare", content: "Write a short poem or story on the spot." },
  { id: 13, type: "dare", content: "Do a random act of kindness for someone you don't know." },
  { id: 14, type: "dare", content: "Learn a magic trick and perform it." },
  { id: 15, type: "dare", content: "Create a piece of artwork using any materials available." },
  { id: 16, type: "dare", content: "Perform a funny dance routine." },
  { id: 17, type: "dare", content: "Try a new hairstyle or hair accessory." },
  { id: 18, type: "dare", content: "Take a cold shower." },
  { id: 19, type: "dare", content: "Write a short love letter or poem to a fictional character." },
  { id: 20, type: "dare", content: "Learn a magic trick and perform it." },
  { id: 21, type: "dare", content: "Do a cartwheel or attempt a gymnastics move." },
  { id: 22, type: "dare", content: "Perform an impression of a famous person." },
  { id: 23, type: "dare", content: "Try a new type of food or cuisine." },
  { id: 24, type: "dare", content: "Do a random act of kindness for a friend or family member." },
  { id: 25, type: "dare", content: "Take a self-portrait using a creative pose or expression." }
];
