export default [
  { id: 1, type: "question", content: "What is your favorite hobby?" },
  { id: 2, type: "question", content: "What's the most adventurous thing you've ever done?" },
  { id: 3, type: "question", content: "What kind of music do you enjoy?" },
  { id: 4, type: "question", content: "What's your favorite travel destination?" },
  { id: 5, type: "question", content: "Do you have any pets? If so, what are they?" },
  { id: 6, type: "question", content: "What's your favorite book or movie?" },
  { id: 7, type: "question", content: "What's your dream job?" },
  { id: 8, type: "question", content: "What's your favorite way to spend a weekend?" },
  { id: 9, type: "question", content: "What's your go-to comfort food?" },
  { id: 10, type: "question", content: "If you could have any superpower, what would it be?" },
  { id: 11, type: "question", content: "What's your favorite season?" },
  { id: 12, type: "question", content: "What's your most treasured possession?" },
  { id: 13, type: "question", content: "What's your favorite type of cuisine?" },
  { id: 14, type: "question", content: "What's your favorite way to relax?" },
  { id: 15, type: "question", content: "What's your favorite childhood memory?" },
  { id: 16, type: "question", content: "What's your favorite TV show?" },
  { id: 17, type: "question", content: "If you could travel back in time, which era would you choose?" },
  { id: 18, type: "question", content: "What's your favorite sport or physical activity?" },
  { id: 19, type: "question", content: "What's the most valuable lesson life has taught you so far?" },
  { id: 20, type: "question", content: "Do you enjoy cooking? If so, what do you like to cook?" },
  { id: 21, type: "question", content: "What's your favorite way to exercise or stay fit?" },
  { id: 22, type: "question", content: "What's your favorite type of art (painting, sculpture, etc.)?" },
  { id: 23, type: "question", content: "If you could have dinner with any historical figure, who would it be?" },
  { id: 24, type: "question", content: "What's your favorite type of dessert?" },
  { id: 25, type: "question", content: "What's your dream travel destination?" }
];

