export default {
	"locations": [
			{
					"id": 6856,
					"name": "Cascade West Grub & Alehouse",
					"street": "64 SW Century Dr",
					"city": "Bend",
					"state": "OR",
					"zip": "97702",
					"lat": "44.0504497",
					"lon": "-121.3314086",
					"zone_id": null,
					"location_type_id": 14,
					"operator_id": null,
					"is_stern_army": null,
					"country": "US",
					"ic_active": null,
					"last_updated_by_username": "signpimp",
					"num_machines": 2
			},
			{
					"id": 17063,
					"name": "Chicken Bonz",
					"street": "143 SW Century Drive",
					"city": "Bend",
					"state": "OR",
					"zip": "97702",
					"lat": "44.0493061",
					"lon": "-121.332257",
					"zone_id": null,
					"location_type_id": 14,
					"operator_id": null,
					"is_stern_army": null,
					"country": "US",
					"ic_active": null,
					"last_updated_by_username": "flipstream",
					"num_machines": 1
			},
			{
					"id": 16618,
					"name": "Clock Tower Pub",
					"street": "2757 NW 7th St # G",
					"city": "Redmond",
					"state": "OR",
					"zip": "97756",
					"lat": "44.3014767",
					"lon": "-121.1755454",
					"zone_id": null,
					"location_type_id": 14,
					"operator_id": null,
					"is_stern_army": null,
					"country": "US",
					"ic_active": null,
					"last_updated_by_username": "pinballgypsy",
					"num_machines": 1
			},
			{
					"id": 16977,
					"name": "Crooked Roots Brewing",
					"street": "420 N Main St",
					"city": "Prineville",
					"state": "OR",
					"zip": "97754",
					"lat": "44.3041816",
					"lon": "-120.8466999",
					"zone_id": null,
					"location_type_id": 62,
					"operator_id": null,
					"is_stern_army": false,
					"country": "US",
					"ic_active": null,
					"last_updated_by_username": "BendPinAdmin",
					"num_machines": 1
			},
			{
					"id": 8093,
					"name": "Double J Saloon",
					"street": "528 SW 6th St",
					"city": "Redmond",
					"state": "OR",
					"zip": "97756",
					"lat": "44.2720495",
					"lon": "-121.1739592",
					"zone_id": null,
					"location_type_id": 4,
					"operator_id": null,
					"is_stern_army": null,
					"country": "US",
					"ic_active": null,
					"last_updated_by_username": "bradleyballer",
					"num_machines": 1
			},
			{
					"id": 7105,
					"name": "Hardtail Bar & Grill",
					"street": "175 N Larch St",
					"city": "Sisters",
					"state": "OR",
					"zip": "97759",
					"lat": "44.29186",
					"lon": "-121.5466187",
					"zone_id": null,
					"location_type_id": 4,
					"operator_id": null,
					"is_stern_army": null,
					"country": "US",
					"ic_active": null,
					"last_updated_by_username": "dt",
					"num_machines": 1
			},
			{
					"id": 13579,
					"name": "La Pine Bowl",
					"street": "52510 US-97",
					"city": "La Pine",
					"state": "OR",
					"zip": "97739",
					"lat": "43.7082501",
					"lon": "-121.4744913",
					"zone_id": null,
					"location_type_id": 10,
					"operator_id": null,
					"is_stern_army": null,
					"country": "US",
					"ic_active": null,
					"last_updated_by_username": "BendPinAdmin",
					"num_machines": 1
			},
			{
					"id": 6850,
					"name": "M & J Tavern",
					"street": "102 NW Greenwood Ave",
					"city": "Bend",
					"state": "OR",
					"zip": "97701",
					"lat": "44.060179",
					"lon": "-121.3089843",
					"zone_id": null,
					"location_type_id": 4,
					"operator_id": null,
					"is_stern_army": null,
					"country": "US",
					"ic_active": null,
					"last_updated_by_username": "pinballgypsy",
					"num_machines": 2
			},
			{
					"id": 7628,
					"name": "Mountain Jug",
					"street": "56805 Venture Ln",
					"city": "Sunriver",
					"state": "OR",
					"zip": "97707",
					"lat": "43.8660282",
					"lon": "-121.4359872",
					"zone_id": null,
					"location_type_id": 4,
					"operator_id": null,
					"is_stern_army": false,
					"country": "US",
					"ic_active": null,
					"last_updated_by_username": "pbm",
					"num_machines": 1
			},
			{
					"id": 16740,
					"name": "Pappy's Pizza",
					"street": "1655 NW 6th St",
					"city": "Redmond",
					"state": "OR",
					"zip": "97756",
					"lat": "44.2913352",
					"lon": "-121.174483",
					"zone_id": null,
					"location_type_id": 30,
					"operator_id": null,
					"is_stern_army": null,
					"country": "US",
					"ic_active": null,
					"last_updated_by_username": "pinballgypsy",
					"num_machines": 1
			},
			{
					"id": 13571,
					"name": "Ponderosa Pizza Parlor",
					"street": "52574 US-97",
					"city": "La Pine",
					"state": "OR",
					"zip": "97739",
					"lat": "43.7099552",
					"lon": "-121.4740941",
					"zone_id": null,
					"location_type_id": 30,
					"operator_id": null,
					"is_stern_army": null,
					"country": "US",
					"ic_active": null,
					"last_updated_by_username": "eme",
					"num_machines": 1
			},
			{
					"id": 6859,
					"name": "Reed Pub",
					"street": "1141 SE Centennial Ct #1",
					"city": "Bend",
					"state": "OR",
					"zip": "97702",
					"lat": "44.0374232",
					"lon": "-121.2916949",
					"zone_id": null,
					"location_type_id": 4,
					"operator_id": null,
					"is_stern_army": null,
					"country": "US",
					"ic_active": null,
					"last_updated_by_username": "pinballgypsy",
					"num_machines": 2
			},
			{
					"id": 11971,
					"name": "Sun Mountain Fun Center",
					"street": "300 NE Bend River Mall Dr",
					"city": "Bend",
					"state": "OR",
					"zip": "97701",
					"lat": "44.0850334",
					"lon": "-121.3022671",
					"zone_id": null,
					"location_type_id": 39,
					"operator_id": null,
					"is_stern_army": false,
					"country": "US",
					"ic_active": null,
					"last_updated_by_username": "flipstream",
					"num_machines": 1
			},
			{
					"id": 10209,
					"name": "The Hideaway Tavern",
					"street": "939 SE 2nd St",
					"city": "Bend",
					"state": "OR",
					"zip": "97702",
					"lat": "44.040927",
					"lon": "-121.3043905",
					"zone_id": null,
					"location_type_id": 14,
					"operator_id": null,
					"is_stern_army": null,
					"country": "US",
					"ic_active": null,
					"last_updated_by_username": "darc.myer",
					"num_machines": 1
			},
			{
					"id": 6849,
					"name": "Vector Volcano Classic Arcade",
					"street": "111 NW Oregon Ave",
					"city": "Bend",
					"state": "OR",
					"zip": "97701",
					"lat": "44.0590861",
					"lon": "-121.3127303",
					"zone_id": null,
					"location_type_id": 3,
					"operator_id": null,
					"is_stern_army": null,
					"country": "US",
					"ic_active": null,
					"last_updated_by_username": "vectorvolcano",
					"num_machines": 7
			},
			{
					"id": 13570,
					"name": "Vic's Bar & Grill",
					"street": "16980 Burgess Rd",
					"city": "La Pine",
					"state": "OR",
					"zip": "97739",
					"lat": "43.7041492",
					"lon": "-121.4781196",
					"zone_id": null,
					"location_type_id": 14,
					"operator_id": null,
					"is_stern_army": null,
					"country": "US",
					"ic_active": null,
					"last_updated_by_username": "jpins",
					"num_machines": 1
			}
	]
}